version: "3.8"

services:

  reycoin-node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: reycoin/reycoin:0.2.0
    container_name: reycoin-node
    environment:
      REYCOIN_DATABASE_USER: "user"
      REYCOIN_DATABASE_PASSWORD: "password"
      REYCOIN_DATABASE_NAME: "reycoin"
      REYCOIN_DATABASE_HOST: "reycoin-postgres"
    tty: true
    ports:
      - 3006:3006
    networks:
      - reycoin

  reycoin-postgres:
    image: postgres:14.1-alpine3.15
    container_name: reycoin-postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "reycoin"
      POSTGRES_HOST: "reycoin-postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - reycoin

  reycoin-adminer:
    image: adminer:4.8.1
    container_name: reycoin-adminer
    ports:
      - "8080:8080"
    networks:
      - reycoin

networks:
  reycoin:
    driver: bridge